/**
 * Recommended reading, keyed to majors.
 *
 * This list was previously duplicated in StudentDashboard and AdminDashboard,
 * with the admin copy silently missing the `majors` field.
 */

export interface Book {
  title: string;
  author: string;
  tagAr: string;
  tagEn: string;
  color: string;
  link: string;
  majors: string[];
}

const ALL_MAJORS = [
  'Cyber and Information Security',
  'Network Computing',
  'Software Engineering',
  'Data Science and Artificial Intelligence',
  'Information Systems',
  'Common',
];

// Palette shortcuts, so a specialization reads as one colour across the shelf.
const CORE = 'bg-slate-100 text-slate-800';
const NET = 'bg-blue-100 text-blue-800';
const SE = 'bg-emerald-100 text-emerald-800';
const CYBER = 'bg-red-100 text-red-800';
const AI = 'bg-purple-100 text-purple-800';
const IS = 'bg-orange-100 text-orange-800';

const CYBER_MAJOR = ['Cyber and Information Security'];
const NET_MAJOR = ['Network Computing'];
const SE_MAJOR = ['Software Engineering'];

export const BOOKS: Book[] = [
  // -- General academic skills & programming foundations (all majors) --------
  {
    title: 'Introduction to Algorithms',
    author: 'Thomas H. Cormen et al.',
    tagAr: 'أساسيات',
    tagEn: 'Foundations',
    color: CORE,
    link: 'https://mitpress.mit.edu/9780262046305/introduction-to-algorithms/',
    majors: ALL_MAJORS,
  },
  {
    title: 'Structure and Interpretation of Computer Programs',
    author: 'Harold Abelson & Gerald J. Sussman',
    tagAr: 'أساسيات البرمجة',
    tagEn: 'Programming',
    color: CORE,
    link: 'https://mitpress.mit.edu/9780262510875/structure-and-interpretation-of-computer-programs/',
    majors: ALL_MAJORS,
  },
  {
    title: 'The Pragmatic Programmer',
    author: 'Andrew Hunt & David Thomas',
    tagAr: 'مهارات مهنية',
    tagEn: 'Craft',
    color: CORE,
    link: 'https://pragprog.com/titles/tpp20/the-pragmatic-programmer-20th-anniversary-edition/',
    majors: ALL_MAJORS,
  },
  {
    title: 'A Mind for Numbers',
    author: 'Barbara Oakley',
    tagAr: 'مهارات دراسية',
    tagEn: 'Study Skills',
    color: CORE,
    link: 'https://barbaraoakley.com/books/a-mind-for-numbers/',
    majors: ALL_MAJORS,
  },
  {
    title: 'Discrete Mathematics and Its Applications',
    author: 'Kenneth H. Rosen',
    tagAr: 'رياضيات',
    tagEn: 'Mathematics',
    color: CORE,
    link: 'https://www.mheducation.com/highered/product/discrete-mathematics-its-applications-rosen.html',
    majors: ALL_MAJORS,
  },
  {
    title: 'Python Crash Course',
    author: 'Eric Matthes',
    tagAr: 'أساسيات البرمجة',
    tagEn: 'Programming',
    color: CORE,
    link: 'https://nostarch.com/python-crash-course-3rd-edition',
    majors: ALL_MAJORS,
  },

  // -- Cyber & Information Security -------------------------------------------
  {
    title: 'Security Engineering',
    author: 'Ross Anderson',
    tagAr: 'أمن سيبراني',
    tagEn: 'Cyber Security',
    color: CYBER,
    link: 'https://www.cl.cam.ac.uk/~rja14/book.html',
    majors: ['Cyber and Information Security', 'Network Computing'],
  },
  {
    title: 'Computer Security: Principles and Practice',
    author: 'William Stallings & Lawrie Brown',
    tagAr: 'أمن سيبراني',
    tagEn: 'Cyber Security',
    color: CYBER,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/computer-security-principles-and-practice/P200000003493/9780134794105',
    majors: CYBER_MAJOR,
  },
  {
    title: 'Cryptography and Network Security',
    author: 'William Stallings',
    tagAr: 'تشفير',
    tagEn: 'Cryptography',
    color: CYBER,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/cryptography-and-network-security-principles-and-practice/P200000003477/9780135764039',
    majors: ['Cyber and Information Security', 'Network Computing'],
  },
  {
    title: 'The Web Application Hacker’s Handbook',
    author: 'Dafydd Stuttard & Marcus Pinto',
    tagAr: 'اختبار الاختراق',
    tagEn: 'Pen Testing',
    color: CYBER,
    link: 'https://www.wiley.com/en-us/The+Web+Application+Hacker%27s+Handbook%2C+2nd+Edition-p-9781118026472',
    majors: CYBER_MAJOR,
  },
  {
    title: 'Practical Malware Analysis',
    author: 'Michael Sikorski & Andrew Honig',
    tagAr: 'تحليل البرمجيات الخبيثة',
    tagEn: 'Malware',
    color: CYBER,
    link: 'https://nostarch.com/malware',
    majors: CYBER_MAJOR,
  },

  // -- Network Computing -----------------------------------------------------
  {
    title: 'Computer Networking: A Top-Down Approach',
    author: 'James Kurose & Keith Ross',
    tagAr: 'شبكات',
    tagEn: 'Networks',
    color: NET,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/computer-networking-a-top-down-approach/P200000003336/9780136681557',
    majors: ['Network Computing', 'Cyber and Information Security'],
  },
  {
    title: 'Computer Networks',
    author: 'Andrew S. Tanenbaum & David J. Wetherall',
    tagAr: 'شبكات',
    tagEn: 'Networks',
    color: NET,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/computer-networks/P200000003480/9780132126953',
    majors: NET_MAJOR,
  },
  {
    title: 'TCP/IP Illustrated, Volume 1',
    author: 'Kevin R. Fall & W. Richard Stevens',
    tagAr: 'بروتوكولات',
    tagEn: 'Protocols',
    color: NET,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/tcpip-illustrated-volume-1-the-protocols/P200000009445/9780321336316',
    majors: NET_MAJOR,
  },
  {
    title: 'CCNA 200-301 Official Cert Guide',
    author: 'Wendell Odom',
    tagAr: 'شهادات شبكات',
    tagEn: 'Certification',
    color: NET,
    link: 'https://www.ciscopress.com/store/ccna-200-301-official-cert-guide-library-9780138221294',
    majors: NET_MAJOR,
  },

  // -- Software Engineering --------------------------------------------------
  {
    title: 'Clean Code',
    author: 'Robert C. Martin',
    tagAr: 'هندسة برمجيات',
    tagEn: 'Software Eng',
    color: SE,
    link: 'https://www.oreilly.com/library/view/clean-code-a/9780136083238/',
    majors: ['Software Engineering', 'Information Systems'],
  },
  {
    title: 'Software Engineering',
    author: 'Ian Sommerville',
    tagAr: 'هندسة برمجيات',
    tagEn: 'Software Eng',
    color: SE,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/software-engineering/P200000003258/9780137035151',
    majors: SE_MAJOR,
  },
  {
    title: 'Design Patterns',
    author: 'Erich Gamma et al. (Gang of Four)',
    tagAr: 'أنماط التصميم',
    tagEn: 'Patterns',
    color: SE,
    link: 'https://www.oreilly.com/library/view/design-patterns-elements/0201633612/',
    majors: SE_MAJOR,
  },
  {
    title: 'Designing Data-Intensive Applications',
    author: 'Martin Kleppmann',
    tagAr: 'أنظمة البيانات',
    tagEn: 'Data Systems',
    color: SE,
    link: 'https://dataintensive.net/',
    majors: ['Software Engineering', 'Data Science and Artificial Intelligence'],
  },
  {
    title: 'Refactoring',
    author: 'Martin Fowler',
    tagAr: 'هندسة برمجيات',
    tagEn: 'Software Eng',
    color: SE,
    link: 'https://martinfowler.com/books/refactoring.html',
    majors: SE_MAJOR,
  },

    // -- General Computer Science & Programming Foundations (expanded) --------
  {
    title: 'Computer Science Distilled',
    author: 'Wladston Ferreira Filho',
    tagAr: 'أساسيات الحوسبة',
    tagEn: 'CS Foundations',
    color: CORE,
    link: 'https://www.manning.com/books/computer-science-distilled',
    majors: ALL_MAJORS,
  },
  {
    title: 'A Beginner\'s Guide to Python 3 Programming',
    author: 'John Hunt',
    tagAr: 'أساسيات البرمجة',
    tagEn: 'Programming',
    color: CORE,
    link: 'https://www.apress.com/gp/book/9781484235973',
    majors: ALL_MAJORS,
  },
  {
    title: 'Head First Java',
    author: 'Bert Bates & Kathy Sierra',
    tagAr: 'أساسيات البرمجة',
    tagEn: 'Programming',
    color: CORE,
    link: 'https://www.oreilly.com/library/view/head-first-java/9781491910770/',
    majors: ALL_MAJORS,
  },
  {
    title: 'Introduction to the Theory of Computation',
    author: 'Michael Sipser',
    tagAr: 'نظرية الحوسبة',
    tagEn: 'Theory',
    color: CORE,
    link: 'https://www.cengage.com/c/product/Introduction-to-the-Theory-of-Computation-3rd-Edition/p/9781133187790',
    majors: ALL_MAJORS,
  },
  {
    title: 'Computability and Logic',
    author: 'George Boolos & John Burgess & Richard Jeffrey',
    tagAr: 'المنطق الحسابي',
    tagEn: 'Logic',
    color: CORE,
    link: 'https://www.cambridge.org/core/books/computability-and-logic/6E8F575A34B35A167E9F0F5797B243FA',
    majors: ALL_MAJORS,
  },
  {
    title: 'The Algorithm Design Manual',
    author: 'Steven S. Skiena',
    tagAr: 'تصميم الخوارزميات',
    tagEn: 'Algorithms',
    color: CORE,
    link: 'https://www.springer.com/gp/book/9781849967204',
    majors: ALL_MAJORS,
  },
  {
    title: 'Fundamentals of Computer Networking',
    author: 'Edward Ross',
    tagAr: 'أساسيات الشبكات',
    tagEn: 'Networking',
    color: NET,
    link: 'https://www.manning.com/books/fundamentals-of-computer-networking',
    majors: ['Common', 'Network Computing'],
  },
  {
    title: 'Operating Systems: Three Easy Pieces',
    author: 'Remzi H. Arpaci-Dusseau & Andrea C. Arpaci-Dusseau',
    tagAr: 'نظم التشغيل',
    tagEn: 'Operating Systems',
    color: CORE,
    link: 'https://pages.cs.wisc.edu/~remzi/OSTEP/',
    majors: ALL_MAJORS,
  },
  {
    title: 'Database Design for Mere Mortals',
    author: 'Michael J. Hernandez',
    tagAr: 'تصميم قواعد البيانات',
    tagEn: 'Databases',
    color: CORE,
    link: 'https://www.informit.com/store/database-design-for-mere-mortals-9780137949076',
    majors: ALL_MAJORS,
  },
  {
    title: 'Clean Architecture: A Craftsman\'s Guide to Software Structure and Design',
    author: 'Robert C. Martin',
    tagAr: 'معمارية البرمجيات',
    tagEn: 'Architecture',
    color: SE,
    link: 'https://www.oreilly.com/library/view/clean-architecture-a/9780134494166/',
    majors: ALL_MAJORS,
  },
  {
    title: 'Computer Organization and Design RISC-V Edition',
    author: 'David A. Patterson & John L. Hennessy',
    tagAr: 'تنظيم الحاسوب',
    tagEn: 'Computer Org',
    color: CORE,
    link: 'https://www.elsevier.com/books/computer-organization-and-design-risc-v-edition/patterson-9780128122754',
    majors: ALL_MAJORS,
  },
  {
    title: 'Computer Networks: An Open Source Approach to Learning',
    author: 'Kurose & Ross',
    tagAr: 'أساسيات الشبكات',
    tagEn: 'Networking',
    color: NET,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/computer-networks-an-open-source/P200000006136/9780136079415',
    majors: ['Common', 'Network Computing'],
  },
  {
    title: 'Software Architecture: The Hard Parts',
    author: 'Neal Ford, Mark Richards, Pramod Sadalage & Zhamak Dehghani',
    tagAr: 'معمارية البرمجيات',
    tagEn: 'Architecture',
    color: SE,
    link: 'https://www.oreilly.com/library/view/software-architecture-the/9781098128029/',
    majors: ['Common', 'Software Engineering'],
  },
  {
    title: 'Modern Operating Systems',
    author: 'Andrew S. Tanenbaum',
    tagAr: 'نظم التشغيل الحديثة',
    tagEn: 'Operating Systems',
    color: CORE,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/modern-operating-systems/P200000003482/9780136006633',
    majors: ALL_MAJORS,
  },
  // -- General Foundations (all-inclusive) ----------------------------------
  {
    title: 'Algorithms Unlocked',
    author: 'Thomas H. Cormen',
    tagAr: 'أساسيات الخوارزميات',
    tagEn: 'Algorithms',
    color: CORE,
    link: 'https://mitpress.mit.edu/9780262526663/algorithms-unlocked/',
    majors: ALL_MAJORS,
  },
  {
    title: 'Introduction to Algorithms (CLRS) — Brief Edition',
    author: 'Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein',
    tagAr: 'خوارزميات أساسية',
    tagEn: 'Algorithms',
    color: CORE,
    link: 'https://mitpress.mit.edu/9780262046305/introduction-to-algorithms/',
    majors: ALL_MAJORS,
  },
  // -- Data Structures & Algorithms in Java -------------------------------
  {
    title: 'Data Structures and Algorithms in Java',
    author: 'Robert Lafore',
    tagAr: 'هياكل البيانات والخوارزميات',
    tagEn: 'Data Structures',
    color: CORE,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/data-structures-and-algorithms-in-java/P200000006040/9780672337403',
    majors: ALL_MAJORS,
  },

  // -- Cyber & Information Security (expanded) ----------------------------
  {
    title: 'Cybersecurity and Cyberwarfare',
    author: 'Charles J. Brooks & Andrew J. Moore',
    tagAr: 'أمن المعلومات',
    tagEn: 'Info Security',
    color: CYBER,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/cybersecurity-and-cyberwarfare/P200000003481/9780132972200',
    majors: ['Cyber and Information Security', 'Common'],
  },
  {
    title: 'Industrial Network Security',
    author: 'Eric Chien',
    tagAr: 'أمن الشبكات الصناعية',
    tagEn: 'Industrial Security',
    color: CYBER,
    link: 'https://www.apress.com/gp/book/9781484208304',
    majors: ['Cyber and Information Security', 'Network Computing'],
  },
  {
    title: 'The Shellcoder\'s Handbook',
    author: 'Chris Anley, John Heasman, Felix Lindner & Gerardo Richarte',
    tagAr: 'اختبار الاختراق المتقدم',
    tagEn: 'Advanced Pen Testing',
    color: CYBER,
    link: 'https://www.wiley.com/en-us/The+Shellcoder%27s+Handbook%2C+2nd+Edition-p-9781118026489',
    majors: CYBER_MAJOR,
  },
  {
    title: 'Incident Response and Computer Forensics',
    author: 'Paul A. Biegler, Michael J. Mulvey, Andrew J. Honig & Lawrence J. Flynn',
    tagAr: 'الاستجابة للحوادث',
    tagEn: 'Incident Response',
    color: CYBER,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/incident-response-and-computer-forensics-3rd-edition/P200000003483/9780133035342',
    majors: ['Cyber and Information Security', 'Network Computing', 'Software Engineering'],
  },
  {
    title: 'Cyber Threat Intelligence',
    author: 'Cody L. Blue, Scott M. Layton & Andrew J. Honig',
    tagAr: 'استخبارات التهديدات',
    tagEn: 'Threat Intel',
    color: CYBER,
    link: 'https://www.apress.com/gp/book/9781484231197',
    majors: CYBER_MAJOR,
  },
  {
    title: 'Blue Team Handbook',
    author: 'Don Murdoch',
    tagAr: 'الدفاع الأمني',
    tagEn: 'Blue Team',
    color: CYBER,
    link: 'https://www.riotpoint.net/BlueTeamHandbook/',
    majors: CYBER_MAJOR,
  },
  {
    title: 'Applied Network Security Monitoring',
    author: 'Chris Sanders & Jason Smith',
    tagAr: 'مراقبة الشبكة',
    tagEn: 'NSM',
    color: CYBER,
    link: 'https://nostarch.com/Applied-Network-Security-Monitoring',
    majors: ['Cyber and Information Security', 'Network Computing'],
  },
  {
    title: 'Intelligence-Driven Incident Response',
    author: 'Scott Roberts, Rebekah Brown & Robert M. Slade',
    tagAr: 'استجابة الحوادث',
    tagEn: 'Incident Response',
    color: CYBER,
    link: 'https://www.oreilly.com/library/view/intelligence-driven-incident-response/9780128027006/',
    majors: CYBER_MAJOR,
  },
  {
    title: 'The Art of Intrusion',
    author: 'Kevin D. Mitnick & William L. Simon',
    tagAr: 'الاختراق',
    tagEn: 'Hacking',
    color: CYBER,
    link: 'https://www.wiley.com/en-us/The+Art+of+Intrusion-p-9780470347335',
    majors: CYBER_MAJOR,
  },
  {
    title: 'Firewalls and Internet Security',
    author: 'William R. Cheswick, Steven M. Bellovin & Aviel D. Rubin',
    tagAr: 'جدران الحماية',
    tagEn: 'Firewalls',
    color: CYBER,
    link: 'https://www.amazon.com/Firewalls-Internet-Security-Replicating-Internet/dp/020163466X',
    majors: ['Cyber and Information Security', 'Network Computing', 'Software Engineering'],
  },
  // -- Software Engineering (expanded) ------------------------------------
  {
    title: 'Software Engineering: A Practitioner\'s Approach',
    author: 'Roger S. Pressman',
    tagAr: 'هندسة البرمجيات',
    tagEn: 'Software Eng',
    color: SE,
    link: 'https://www.mheducation.com/highered/product/software-engineering-practitioners-approach-pressman/R00000004533.html',
    majors: SE_MAJOR,
  },
  {
    title: 'Agile Software Development',
    author: 'Robert C. Martin',
    tagAr: 'تطوير أجايل',
    tagEn: 'Agile',
    color: SE,
    link: 'https://www.oreilly.com/library/view/agile-software-development/9780132782593/',
    majors: SE_MAJOR,
  },
  {
    title: 'Software Project Management',
    author: 'Steve McConnell',
    tagAr: 'إدارة المشاريع',
    tagEn: 'Project Mgmt',
    color: SE,
    link: 'https://www.microsoftpressstore.com/store/software-project-management-a-modern-approach-9781509302418',
    majors: SE_MAJOR,
  },
  {
    title: 'Rapid Development',
    author: 'Steve McConnell',
    tagAr: 'تطوير سريع',
    tagEn: 'Rapid Dev',
    color: SE,
    link: 'https://www.microsoftpressstore.com/store/rapid-development-9781509348638',
    majors: SE_MAJOR,
  },
  {
    title: 'Software Estimation: Demystifying the Black Art',
    author: 'Steve McConnell',
    tagAr: 'تقدير المشاريع',
    tagEn: 'Estimation',
    color: SE,
    link: 'https://www.microsoftpressstore.com/store/software-estimation-9780735622465',
    majors: SE_MAJOR,
  },
  {
    title: 'Release It!',
    author: 'Michael T. Nygard',
    tagAr: 'إصدار البرمجيات',
    tagEn: 'Release',
    color: SE,
    link: 'https://www.oreilly.com/library/view/release-it/9781680502395/',
    majors: SE_MAJOR,
  },
  {
    title: 'Fundamentals of Software Engineering',
    author: 'Frank L. Friedman & Joel R. Nelson',
    tagAr: 'أساسيات هندسة البرمجيات',
    tagEn: 'Software Eng',
    color: SE,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/fundamentals-of-software-engineering/P200000003174/9780131091093',
    majors: SE_MAJOR,
  },
  {
    title: 'Object-Oriented Software Construction',
    author: 'Bertrand Meyer',
    tagAr: 'البرمجة الكائنية',
    tagEn: 'OOP',
    color: SE,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/object-oriented-software-construction/P200000001714/9780136290490',
    majors: SE_MAJOR,
  },
  {
    title: 'A Pattern Language',
    author: 'Christopher Alexander',
    tagAr: 'أنماط التصميم',
    tagEn: 'Patterns',
    color: SE,
    link: 'https://www.oreilly.com/library/view/a-pattern-language/9780195019191/',
    majors: ALL_MAJORS,
  },
  {
    title: 'Software Craftsmanship',
    author: 'Pete McBreen',
    tagAr: 'حرفية البرمجيات',
    tagEn: 'Craft',
    color: SE,
    link: 'https://www.amazon.com/Software-Craftsmanship-Professional-Excellence-Application/dp/0131177052',
    majors: SE_MAJOR,
  },
  {
    title: 'The Timeless Way of Writing',
    author: 'Christopher Alexander',
    tagAr: 'التصميم البرمجي',
    tagEn: 'Design Patterns',
    color: SE,
    link: 'https://www.oreilly.com/library/view/the-timeless-way/9780195024793/',
    majors: SE_MAJOR,
  },
  // -- Network Computing (expanded) ---------------------------------------
  {
    title: 'Computer Networks: A Systems Approach, 6th Edition',
    author: 'Larry L. Peterson & Bruce S. Davie',
    tagAr: 'شبكات الحاسوب',
    tagEn: 'Networks',
    color: NET,
    link: 'https://book.systemsapproach.org/',
    majors: ['Network Computing', 'Common'],
  },
  {
    title: 'Computer Networking: A Top-Down Approach, 7th Edition',
    author: 'James Kurose & Keith Ross',
    tagAr: 'شبكات الحاسوب',
    tagEn: 'Networks',
    color: NET,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/computer-networking-a-top-down-approach/P200000003336/9780136681557',
    majors: ['Network Computing', 'Common'],
  },
  {
    title: 'Computer Networks, 5th Edition',
    author: 'Andrew S. Tanenbaum & David J. Wetherall',
    tagAr: 'شبكات الحاسوب',
    tagEn: 'Networks',
    color: NET,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/computer-networks/P200000003480/9780132126953',
    majors: NET_MAJOR,
  },
  {
    title: 'Computer Networks: A Systems Approach, 6th Edition (Workbook)',
    author: 'Larry L. Peterson & Bruce S. Davie',
    tagAr: 'تمارين الشبكات',
    tagEn: 'Networking Labs',
    color: NET,
    link: 'https://book.systemsapproach.org/',
    majors: ['Network Computing', 'Common'],
  },
  {
    title: 'Computer Systems: A Programmer\'s Perspective, 3rd Edition',
    author: 'Randal E. Bryant & David R. O\'Hallaron',
    tagAr: 'أنظمة الحاسوب',
    tagEn: 'Systems',
    color: NET,
    link: 'https://csapp.cs.cmu.edu/',
    majors: ['Network Computing', 'Common'],
  },
  {
    title: 'Computer Network Architecture and Design',
    author: 'Janai A. Nelson & Michael A. Davis',
    tagAr: 'بنية الشبكات',
    tagEn: 'Network Arch',
    color: NET,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/computer-network-architecture-and-design/P200000009458/9780134845590',
    majors: ['Network Computing', 'Cyber and Information Security'],
  },
  {
    title: 'Network Security: Private Communication in a Public World',
    author: 'Charlie Kaufman, Radia Perlman & Mike Speciner',
    tagAr: 'أمان الشبكات',
    tagEn: 'Network Security',
    color: NET,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/network-security-private-communication/P200000003484/9780136135346',
    majors: ['Network Computing', 'Cyber and Information Security', 'Software Engineering'],
  },
  {
    title: 'Local Area Networks, 3rd Edition',
    author: 'Kenneth C. Clements',
    tagAr: 'الشبكات المحلية',
    tagEn: 'LAN',
    color: NET,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/local-area-networks-3rd-edition/P200000003485/9780136135353',
    majors: NET_MAJOR,
  },
  {
    title: 'Voice over IP: Principles and Practice',
    author: 'Jonathan B. Rosenberg',
    tagAr: 'الاتصالات الصوتية',
    tagEn: 'VoIP',
    color: NET,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/voice-over-ip-principles-and/P200000003486/9780130340706',
    majors: ['Network Computing', 'Common'],
  },
  {
    title: 'Computer Communication Networks, 2nd Edition',
    author: 'C. E. Spurr & J. B. Dennis',
    tagAr: 'شبكات الاتصالات',
    tagEn: 'Comms',
    color: NET,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/computer-communication-networks-2nd/P200000003487/9780131196476',
    majors: ['Network Computing', 'Common'],
  },
  {
    title: 'Next-Generation Firewalls',
    author: 'Gavin Millard',
    tagAr: 'جدران الحماية الحديثة',
    tagEn: 'NG Firewall',
    color: NET,
    link: 'https://www.packtpub.com/en-us/product/next-generation-firewalls-9781782169675',
    majors: ['Network Computing', 'Cyber and Information Security'],
  },
  {
    title: 'Software-Defined Networking',
    author: 'Nick McKeown, Martin Casado & others',
    tagAr: 'الشبكات المعرّفة بالبرمجيات',
    tagEn: 'SDN',
    color: NET,
    link: 'https://www.oreilly.com/library/view/software-defined-networking/9781491951591/',
    majors: ['Network Computing', 'Software Engineering'],
  },
  {
    title: 'Pattern Recognition and Machine Learning',
    author: 'Christopher Bishop',
    tagAr: 'الذكاء الاصطناعي',
    tagEn: 'AI',
    color: AI,
    link: 'https://www.microsoft.com/en-us/research/people/cmbishop/prml-book/',
    majors: ['Data Science and Artificial Intelligence', 'Software Engineering'],
  },
  {
    title: 'Management Information Systems',
    author: 'Kenneth C. Laudon & Jane P. Laudon',
    tagAr: 'نظم المعلومات',
    tagEn: 'Info Systems',
    color: IS,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/management-information-systems-managing-the-digital-firm/P200000001602/9780136971276',
    majors: ['Information Systems'],
  },

  // -- Additional foundations (all majors) -----------------------------------
  {
    title: 'Code: The Hidden Language of Computer Hardware and Software',
    author: 'Charles Petzold',
    tagAr: 'أساسيات الحوسبة',
    tagEn: 'Foundations',
    color: CORE,
    link: 'https://www.charlespetzold.com/code/',
    majors: ALL_MAJORS,
  },
  {
    title: 'The C Programming Language',
    author: 'Brian W. Kernighan & Dennis M. Ritchie',
    tagAr: 'أساسيات البرمجة',
    tagEn: 'Programming',
    color: CORE,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/c-programming-language-the/P200000000368/9780131103627',
    majors: ALL_MAJORS,
  },
  {
    title: 'Operating System Concepts',
    author: 'Silberschatz, Galvin & Gagne',
    tagAr: 'نظم التشغيل',
    tagEn: 'Operating Systems',
    color: CORE,
    link: 'https://www.wiley.com/en-us/Operating+System+Concepts%2C+10th+Edition-p-9781119320913',
    majors: ALL_MAJORS,
  },
  {
    title: 'Database System Concepts',
    author: 'Silberschatz, Korth & Sudarshan',
    tagAr: 'قواعد البيانات',
    tagEn: 'Databases',
    color: CORE,
    link: 'https://www.db-book.com/',
    majors: ALL_MAJORS,
  },

  // -- Cyber & Information Security (more) ------------------------------------
  {
    title: 'Hacking: The Art of Exploitation',
    author: 'Jon Erickson',
    tagAr: 'أمن هجومي',
    tagEn: 'Offensive Security',
    color: CYBER,
    link: 'https://nostarch.com/hacking2.htm',
    majors: CYBER_MAJOR,
  },
  {
    title: 'The Tangled Web: Securing Modern Web Applications',
    author: 'Michal Zalewski',
    tagAr: 'أمن الويب',
    tagEn: 'Web Security',
    color: CYBER,
    link: 'https://nostarch.com/tangledweb',
    majors: CYBER_MAJOR,
  },
  {
    title: 'Applied Cryptography',
    author: 'Bruce Schneier',
    tagAr: 'تشفير',
    tagEn: 'Cryptography',
    color: CYBER,
    link: 'https://www.schneier.com/books/applied-cryptography/',
    majors: ['Cyber and Information Security', 'Network Computing'],
  },
  {
    title: 'Digital Forensics and Incident Response',
    author: 'Gerard Johansen',
    tagAr: 'الأدلة الرقمية',
    tagEn: 'Forensics',
    color: CYBER,
    link: 'https://www.packtpub.com/en-us/product/digital-forensics-and-incident-response-9781803238678',
    majors: CYBER_MAJOR,
  },

  // -- Network Computing (more) ----------------------------------------------
  {
    title: 'Computer Networks: A Systems Approach',
    author: 'Larry L. Peterson & Bruce S. Davie',
    tagAr: 'شبكات',
    tagEn: 'Networks',
    color: NET,
    link: 'https://book.systemsapproach.org/',
    majors: NET_MAJOR,
  },
  {
    title: 'Network Warrior',
    author: 'Gary A. Donahue',
    tagAr: 'إدارة الشبكات',
    tagEn: 'Network Admin',
    color: NET,
    link: 'https://www.oreilly.com/library/view/network-warrior-2nd/9781449307974/',
    majors: NET_MAJOR,
  },
  {
    title: 'Unix and Linux System Administration Handbook',
    author: 'Evi Nemeth et al.',
    tagAr: 'إدارة الأنظمة',
    tagEn: 'Sys Admin',
    color: NET,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/unix-and-linux-system-administration-handbook/P200000009456/9780134277554',
    majors: ['Network Computing', 'Cyber and Information Security'],
  },

  // -- Software Engineering (more) -------------------------------------------
  {
    title: 'The Mythical Man-Month',
    author: 'Frederick P. Brooks Jr.',
    tagAr: 'إدارة المشاريع البرمجية',
    tagEn: 'SE Management',
    color: SE,
    link: 'https://www.oreilly.com/library/view/mythical-man-month-the/0201835959/',
    majors: SE_MAJOR,
  },
  {
    title: 'Domain-Driven Design',
    author: 'Eric Evans',
    tagAr: 'تصميم البرمجيات',
    tagEn: 'Architecture',
    color: SE,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/domain-driven-design-tackling-complexity-in-the-heart-of-software/P200000009375/9780321125217',
    majors: SE_MAJOR,
  },
  {
    title: 'Test-Driven Development: By Example',
    author: 'Kent Beck',
    tagAr: 'اختبار البرمجيات',
    tagEn: 'Testing',
    color: SE,
    link: 'https://www.pearson.com/en-us/subject-catalog/p/test-driven-development-by-example/P200000009349/9780321146533',
    majors: SE_MAJOR,
  },
  {
    title: 'Code Complete',
    author: 'Steve McConnell',
    tagAr: 'هندسة برمجيات',
    tagEn: 'Software Eng',
    color: SE,
    link: 'https://www.microsoftpressstore.com/store/code-complete-9780735619678',
    majors: ['Software Engineering', 'Information Systems'],
  },

  // -- Foundations, systems & programming (all majors) ------------------------
  {
    title: "Computer Systems: A Programmer's Perspective",
    author: 'Randal E. Bryant & David R. O’Hallaron',
    tagAr: 'أنظمة الحاسوب',
    tagEn: 'Systems',
    color: CORE,
    link: 'https://csapp.cs.cmu.edu/',
    majors: ALL_MAJORS,
  },
  {
    title: 'Crafting Interpreters',
    author: 'Robert Nystrom',
    tagAr: 'لغات البرمجة',
    tagEn: 'Languages',
    color: CORE,
    link: 'https://craftinginterpreters.com/',
    majors: ALL_MAJORS,
  },
  {
    title: 'Eloquent JavaScript',
    author: 'Marijn Haverbeke',
    tagAr: 'برمجة الويب',
    tagEn: 'Web Programming',
    color: CORE,
    link: 'https://eloquentjavascript.net/',
    majors: ALL_MAJORS,
  },
  {
    title: 'Automate the Boring Stuff with Python',
    author: 'Al Sweigart',
    tagAr: 'أساسيات البرمجة',
    tagEn: 'Programming',
    color: CORE,
    link: 'https://automatetheboringstuff.com/',
    majors: ALL_MAJORS,
  },
  {
    title: 'Think Python',
    author: 'Allen B. Downey',
    tagAr: 'أساسيات البرمجة',
    tagEn: 'Programming',
    color: CORE,
    link: 'https://greenteapress.com/wp/think-python-2e/',
    majors: ALL_MAJORS,
  },
  {
    title: 'Algorithms, 4th Edition',
    author: 'Robert Sedgewick & Kevin Wayne',
    tagAr: 'خوارزميات',
    tagEn: 'Algorithms',
    color: CORE,
    link: 'https://algs4.cs.princeton.edu/home/',
    majors: ALL_MAJORS,
  },
  {
    title: 'Grokking Algorithms',
    author: 'Aditya Bhargava',
    tagAr: 'خوارزميات',
    tagEn: 'Algorithms',
    color: CORE,
    link: 'https://www.manning.com/books/grokking-algorithms',
    majors: ALL_MAJORS,
  },
  {
    title: 'The Art of Computer Programming',
    author: 'Donald E. Knuth',
    tagAr: 'مرجع متقدم',
    tagEn: 'Reference',
    color: CORE,
    link: 'https://www-cs-faculty.stanford.edu/~knuth/taocp.html',
    majors: ALL_MAJORS,
  },
  {
    title: 'Concrete Mathematics',
    author: 'Graham, Knuth & Patashnik',
    tagAr: 'رياضيات',
    tagEn: 'Mathematics',
    color: CORE,
    link: 'https://www-cs-faculty.stanford.edu/~knuth/gkp.html',
    majors: ALL_MAJORS,
  },
  {
    title: 'Pro Git',
    author: 'Scott Chacon & Ben Straub',
    tagAr: 'أدوات المطوّر',
    tagEn: 'Tooling',
    color: CORE,
    link: 'https://git-scm.com/book/en/v2',
    majors: ALL_MAJORS,
  },
  {
    title: 'The Linux Command Line',
    author: 'William Shotts',
    tagAr: 'سطر الأوامر',
    tagEn: 'Command Line',
    color: CORE,
    link: 'https://linuxcommand.org/tlcl.php',
    majors: ALL_MAJORS,
  },
  {
    title: 'Open Data Structures',
    author: 'Pat Morin',
    tagAr: 'هياكل البيانات',
    tagEn: 'Data Structures',
    color: CORE,
    link: 'https://opendatastructures.org/',
    majors: ALL_MAJORS,
  },
  {
    title: 'Dive Into Systems',
    author: 'Matthews, Newhall & Webb',
    tagAr: 'أنظمة الحاسوب',
    tagEn: 'Systems',
    color: CORE,
    link: 'https://diveintosystems.org/',
    majors: ALL_MAJORS,
  },
  {
    title: 'Head First Design Patterns',
    author: 'Eric Freeman & Elisabeth Robson',
    tagAr: 'أنماط التصميم',
    tagEn: 'Patterns',
    color: CORE,
    link: 'https://www.oreilly.com/library/view/head-first-design/9781492077992/',
    majors: ALL_MAJORS,
  },

  // -- Cyber & Information Security (extended) --------------------------------
  {
    title: "Metasploit: The Penetration Tester's Guide",
    author: 'David Kennedy et al.',
    tagAr: 'اختبار الاختراق',
    tagEn: 'Pen Testing',
    color: CYBER,
    link: 'https://nostarch.com/metasploit',
    majors: CYBER_MAJOR,
  },
  {
    title: 'Black Hat Python',
    author: 'Justin Seitz & Tim Arnold',
    tagAr: 'أمن هجومي',
    tagEn: 'Offensive Security',
    color: CYBER,
    link: 'https://nostarch.com/black-hat-python2E',
    majors: CYBER_MAJOR,
  },
  {
    title: 'Practical Packet Analysis',
    author: 'Chris Sanders',
    tagAr: 'تحليل الحزم',
    tagEn: 'Packet Analysis',
    color: CYBER,
    link: 'https://nostarch.com/packetanalysis3',
    majors: ['Cyber and Information Security', 'Network Computing'],
  },
  {
    title: 'Serious Cryptography',
    author: 'Jean-Philippe Aumasson',
    tagAr: 'تشفير',
    tagEn: 'Cryptography',
    color: CYBER,
    link: 'https://nostarch.com/seriouscrypto',
    majors: CYBER_MAJOR,
  },
  {
    title: 'Threat Modeling: Designing for Security',
    author: 'Adam Shostack',
    tagAr: 'نمذجة التهديدات',
    tagEn: 'Threat Modeling',
    color: CYBER,
    link: 'https://shostack.org/books/threat-modeling-book',
    majors: CYBER_MAJOR,
  },
  {
    title: 'OWASP Web Security Testing Guide',
    author: 'OWASP Foundation',
    tagAr: 'أمن الويب',
    tagEn: 'Web Security',
    color: CYBER,
    link: 'https://owasp.org/www-project-web-security-testing-guide/',
    majors: CYBER_MAJOR,
  },
  {
    title: 'NIST Cybersecurity Framework',
    author: 'NIST',
    tagAr: 'حوكمة الأمن',
    tagEn: 'Governance',
    color: CYBER,
    link: 'https://www.nist.gov/cyberframework',
    majors: ['Cyber and Information Security', 'Information Systems'],
  },
  {
    title: 'Practical Cryptography for Developers',
    author: 'Svetlin Nakov',
    tagAr: 'تشفير تطبيقي',
    tagEn: 'Cryptography',
    color: CYBER,
    link: 'https://cryptobook.nakov.com/',
    majors: ['Cyber and Information Security', 'Software Engineering'],
  },
  {
    title: 'Bulletproof TLS and PKI',
    author: 'Ivan Ristić',
    tagAr: 'أمن الاتصالات',
    tagEn: 'TLS / PKI',
    color: CYBER,
    link: 'https://www.feistyduck.com/books/bulletproof-tls-and-pki/',
    majors: ['Cyber and Information Security', 'Network Computing'],
  },

  // -- Network Computing (extended) -------------------------------------------
  {
    title: "Beej's Guide to Network Programming",
    author: 'Brian “Beej” Hall',
    tagAr: 'برمجة الشبكات',
    tagEn: 'Network Programming',
    color: NET,
    link: 'https://beej.us/guide/bgnet/',
    majors: ['Network Computing', 'Software Engineering'],
  },
  {
    title: 'High Performance Browser Networking',
    author: 'Ilya Grigorik',
    tagAr: 'أداء الشبكات',
    tagEn: 'Performance',
    color: NET,
    link: 'https://hpbn.co/',
    majors: ['Network Computing', 'Software Engineering'],
  },
  {
    title: 'Site Reliability Engineering',
    author: 'Google SRE Team',
    tagAr: 'موثوقية الأنظمة',
    tagEn: 'Reliability',
    color: NET,
    link: 'https://sre.google/sre-book/table-of-contents/',
    majors: ['Network Computing', 'Software Engineering'],
  },
  {
    title: 'Network Programmability and Automation',
    author: 'Edelman, Lowe & Oswalt',
    tagAr: 'أتمتة الشبكات',
    tagEn: 'Automation',
    color: NET,
    link: 'https://www.oreilly.com/library/view/network-programmability-and/9781098110826/',
    majors: NET_MAJOR,
  },
  {
    title: 'Kubernetes: Up and Running',
    author: 'Burns, Beda & Hightower',
    tagAr: 'الحوسبة السحابية',
    tagEn: 'Cloud',
    color: NET,
    link: 'https://www.oreilly.com/library/view/kubernetes-up-and/9781098110192/',
    majors: ['Network Computing', 'Software Engineering'],
  },
  {
    title: 'Routing TCP/IP, Volume 1',
    author: 'Jeff Doyle',
    tagAr: 'التوجيه',
    tagEn: 'Routing',
    color: NET,
    link: 'https://www.ciscopress.com/store/routing-tcp-ip-volume-1-9781587052026',
    majors: NET_MAJOR,
  },
  {
    title: 'DNS and BIND',
    author: 'Cricket Liu & Paul Albitz',
    tagAr: 'خدمات الشبكة',
    tagEn: 'Network Services',
    color: NET,
    link: 'https://www.oreilly.com/library/view/dns-and-bind/0596100574/',
    majors: NET_MAJOR,
  },

  // -- Software Engineering (extended) ----------------------------------------
  {
    title: 'Clean Architecture',
    author: 'Robert C. Martin',
    tagAr: 'معمارية البرمجيات',
    tagEn: 'Architecture',
    color: SE,
    link: 'https://www.oreilly.com/library/view/clean-architecture-a/9780134494272/',
    majors: SE_MAJOR,
  },
  {
    title: 'Working Effectively with Legacy Code',
    author: 'Michael C. Feathers',
    tagAr: 'صيانة الأنظمة',
    tagEn: 'Maintenance',
    color: SE,
    link: 'https://www.oreilly.com/library/view/working-effectively-with/0131177052/',
    majors: SE_MAJOR,
  },
  {
    title: 'Continuous Delivery',
    author: 'Jez Humble & David Farley',
    tagAr: 'التسليم المستمر',
    tagEn: 'DevOps',
    color: SE,
    link: 'https://www.oreilly.com/library/view/continuous-delivery-reliable/9780321670250/',
    majors: ['Software Engineering', 'Network Computing'],
  },
  {
    title: 'Building Microservices',
    author: 'Sam Newman',
    tagAr: 'الخدمات المصغّرة',
    tagEn: 'Microservices',
    color: SE,
    link: 'https://www.oreilly.com/library/view/building-microservices-2nd/9781492034018/',
    majors: SE_MAJOR,
  },
  {
    title: 'Patterns of Enterprise Application Architecture',
    author: 'Martin Fowler',
    tagAr: 'معمارية البرمجيات',
    tagEn: 'Architecture',
    color: SE,
    link: 'https://martinfowler.com/books/eaa.html',
    majors: ['Software Engineering', 'Information Systems'],
  },
  {
    title: 'UML Distilled',
    author: 'Martin Fowler',
    tagAr: 'تحليل وتصميم',
    tagEn: 'Modelling',
    color: SE,
    link: 'https://martinfowler.com/books/uml.html',
    majors: ['Software Engineering', 'Information Systems'],
  },
  {
    title: 'The Clean Coder',
    author: 'Robert C. Martin',
    tagAr: 'الاحتراف المهني',
    tagEn: 'Professionalism',
    color: SE,
    link: 'https://www.oreilly.com/library/view/clean-coder-the/9780132542913/',
    majors: ['Software Engineering', 'Information Systems'],
  },

  // -- Data Science & AI ------------------------------------------------------
  {
    title: 'Artificial Intelligence: A Modern Approach',
    author: 'Stuart Russell & Peter Norvig',
    tagAr: 'الذكاء الاصطناعي',
    tagEn: 'AI',
    color: AI,
    link: 'https://aima.cs.berkeley.edu/',
    majors: ['Data Science and Artificial Intelligence', 'Software Engineering'],
  },
  {
    title: 'Deep Learning',
    author: 'Goodfellow, Bengio & Courville',
    tagAr: 'التعلم العميق',
    tagEn: 'Deep Learning',
    color: AI,
    link: 'https://www.deeplearningbook.org/',
    majors: ['Data Science and Artificial Intelligence'],
  },
  {
    title: 'An Introduction to Statistical Learning',
    author: 'James, Witten, Hastie & Tibshirani',
    tagAr: 'التعلم الإحصائي',
    tagEn: 'Statistics',
    color: AI,
    link: 'https://www.statlearning.com/',
    majors: ['Data Science and Artificial Intelligence'],
  },
  {
    title: 'Python for Data Analysis',
    author: 'Wes McKinney',
    tagAr: 'تحليل البيانات',
    tagEn: 'Data Analysis',
    color: AI,
    link: 'https://wesmckinney.com/book/',
    majors: ['Data Science and Artificial Intelligence', 'Information Systems'],
  },
  {
    title: 'Hands-On Machine Learning',
    author: 'Aurélien Géron',
    tagAr: 'تعلم الآلة',
    tagEn: 'Machine Learning',
    color: AI,
    link: 'https://www.oreilly.com/library/view/hands-on-machine-learning/9781098125967/',
    majors: ['Data Science and Artificial Intelligence', 'Software Engineering'],
  },
];
